name: Deploy Node.js Backend to EC2

on:
  push:
    branches:
      - main # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Yarn
        run: npm install -g yarn

      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/exam-portal-backend
            git pull origin main
            yarn install --production
            sudo pm2 restart all
            # pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js
