name: Deploy Node.js Backend to EC2

on:
  workflow_dispatch: # Manual trigger only
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Verify build output
        run: ls -la dist/

      - name: Deploy built files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/,package.json,ecosystem.config.js"
          target: "/var/www/exam-portal-backend/"
          overwrite: true

      - name: Start application
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/exam-portal-backend
            cp /var/www/exam-portal-backend/.env dist/
            sudo rm -rf node_modules
            npm install --production
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
